#!/bin/bash
ver=0.2
tempdir="/tmp/ccr-tools-$UID"
configrc=$HOME/.config/ccr-tools/config
ccrbaseurl="http://chakra-linux.org/ccr/"
rpcurl="${ccrbaseurl}rpc.php?type"
ccrurl="${ccrbaseurl}packages.php"
idurl="${ccrbaseurl}rpc.php?type=info&arg="
voteurl="${ccrbaseurl}packages.php"
checkurl="${ccrbaseurl}packages.php?ID="
submiturl="${ccrbaseurl}pkgsubmit.php"
libccr='/usr/lib/libccr.sh'

mkdir -p "$tempdir"

# Defining some functions needed by main program

source "$libccr"


die() {
    if [[ -d "$tempdir" && $rememberme != 1 ]]; then
        rm -rf "$tempdir"
    fi
    exit $1
}

err() {
    echo -e "$1"
    die 1
}

version() {
    echo "ccr-tools - version $ver"
    echo
    echo " http://ccr-tools.github.com/"
    exit
}

usage() {
    echo "ccr-tools - version $ver"
    echo
    echo "usage: ccr-tools <option> <pkgname1> <pkgname2> ..."
    echo
    echo "ccr-tools --version,    -V    shows version"
    echo "ccr-tools --help,       -h    shows this help"
    echo "ccr-tools --vote,       -v    vote for packages"
    echo "ccr-tools --unvote,     -u    unvote packages"
    echo "ccr-tools --check,      -c    check for voted packages"
    echo "ccr-tools --submit,     -s    submit a new package"
    echo "          --category,   -C    category for new packages"
    echo "ccr-tools -sC                 list all valid categories"
    echo "ccr-tools --maintainer, -m    list all packages by maintainer"
    echo "ccr-tools --forget,     -f    don't keep cookies"
    echo
    echo " example:  ccr-tools --vote shake bfilter"
    echo
    echo "You can create ~/.config/ccr-tools/config containing:"
    echo "user=YOUR_CCR_USERNAME"
    echo "pass=YOUR_CCR_PASS"
    echo
    echo "To create a new account just go to:"
    echo "http://chakra-linux.org/ccr/account.php"
    exit
}

# Tests whether $1 exists on the ccr
existsinccr() {
    retval=$(curl -LfGs --data-urlencode "arg=$pkgname" "$rpcurl=info" | \
        jshon -Qe type -u)

    [[ $retval = "info" && ! $category ]]
}

### MAIN PROGRAM ###
pkgargs=()
while [ "$#" -ne "0" ]; do
	case $1 in
    --help|-h)     usage ;;
    --version|-V)  version ;;
    --check|-c) shift
        pkgargs=$@
        check
        ;;
    --vote|-v) shift
        pkgargs=$@
        vote
        ;;
    --unvote|-u) shift
        pkgargs=$@
        unvote
        ;;
    --submit|-s) shift
        while [[ "$#" != 0 ]]; do
            case $1 in
            --category|-C) shift 
                category=$1; shift
                [[ $category == "" ]] && listcat
                ;;
            *)  pkgargs+=$1; shift
                ;;
            esac
        done
        submit
        ;;
    -sC) shift
        category=$1; shift
        [[ "$category" == "" ]] && listcat
        pkgargs=$@
        submit
        ;;
    --maintainer|-m) shift 
        maintainer=$1 
        maintainer
        ;;
    --forget|-f) rememberme=0 ;;
    --*|-*) echo "ccr-tools: Option \`$1' is not valid."; exit 5 ;;
	esac
	shift
done

usage

# vim: sts=4 ts=4 sw=4 et
